# Usage:
#     Run API server somewhere, i.e. python api/server.py
#
#     Then run the client:
#     docker run --runtime=nvidia --net=host -it deepdrive python main.py --baseline --is-remote-client
#
#     ppo:
#     mnet weights: https://s3-us-west-1.amazonaws.com/deepdrive/weights/2018-05-22__03-04-53PM.zip
#     baselines results with weights: https://s3-us-west-1.amazonaws.com/deepdrive/weights/baselines_results.zip and change PPO_RESUME_PATH in config.py # TODO: Promote PPO resume path to command line arg
#     docker run -v /mnet_weight_dir/2018-05-22__03-04-53PM:/mnet_weight_dir/2018-05-22__03-04-53PM -v /baselines_results_dir/openai-2018-06-22-00-00-21-866205/checkpoints:/baselines_results_dir/openai-2018-06-22-00-00-21-866205/checkpoints --runtime=nvidia --net=host -it deepdrive python main.py --agent bootstrapped_ppo2 --experiment bootstrap --train --net-path=/mnet_weight_dir/2018-05-22__03-04-53PM/model.ckpt-45466 --sync --is-remote-client

FROM tensorflow/tensorflow:1.8.0-gpu-py3

# Minimize re-downloading / re-installing TODO: Cleanup / do this in python
###########################################################################
WORKDIR /src/deepdrive
COPY docker/agent-requirements.txt .
RUN pip install -r agent-requirements.txt
ENV DEEPDRIVE_DIR=/Deepdrive
ENV DEEPDRIVE_REMOTE_CLIENT=true
###########################################################################

ENV PYTHONPATH=/src/deepdrive

# API Port
EXPOSE 5557/tcp

COPY . .

CMD python main.py