STEP = 'step'
RESET = 'reset'
START = 'start'
ACTION_SPACE = 'action_space'
OBSERVATION_SPACE = 'observation_space'
REWARD_RANGE = 'reward_range'
METADATA = 'metadata'
CHANGE_CAMERAS = 'change_cameras'
